version: '3.8'
services:
    database:
        container_name: shop-main-database
        image: postgres:16.0-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            - shop-api-network

networks:
    shop-api-network:
