version: '3.9'

services:
    api:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: shop-api
        restart: unless-stopped
        user: ${UID}:${GID}
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        depends_on:
            - database
        networks:
           - shop-http-server-network
           - shop-api-network

    database:
        container_name: shop-main-database
        image: postgres:16.0-alpine
        restart: unless-stopped
        ports:
            - "5445:5432"
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        networks:
            shop-api-network:
                aliases:
                    - main-database-host

    nginx:
        image: nginx:1.25.2-alpine
        container_name: shop-http-server
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./storage/logs/nginx:/var/log/nginx/
            - ./docker/nginx/default.template:/etc/nginx/templates/default.conf.template
        depends_on:
            - api
        networks:
            - shop-http-server-network

networks:
    shop-api-network:
    shop-http-server-network:
