<?php

return [
    'server' => '',
    'x-content-type-options' => 'nosniff',
    'x-download-options' => 'noopen',
    'x-frame-options' => 'deny',
    'x-permitted-cross-domain-policies' => 'none',
    'x-powered-by' => '',
    'x-xss-protection' => '0',
    'referrer-policy' => 'no-referrer',
    'cross-origin-embedder-policy' => 'require-corp',
    'cross-origin-opener-policy' => 'same-origin',
    'cross-origin-resource-policy' => 'same-origin',
    'clear-site-data' => [
        'enable' => false,
        'all' => false,
        'cache' => false,
        'cookies' => false,
        'storage' => false,
        'executionContexts' => false,
    ],
    'hsts' => [
        'enable' => true,
        'max-age' => 31536000,
        'include-sub-domains' => false,
        'preload' => false,
    ],
    'expect-ct' => [
        'enable' => false,
        'max-age' => 2147483648,
        'enforce' => false,
        'report-uri' => null,
    ],
    'permissions-policy' => [
        'enable' => true,
        'accelerometer' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'ambient-light-sensor' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'autoplay' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'battery' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'camera' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'cross-origin-isolated' => [
            'none' => false,
            '*' => false,
            'self' => true,
            'origins' => [],
        ],
        'display-capture' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'document-domain' => [
            'none' => false,
            '*' => true,
            'self' => false,
            'origins' => [],
        ],
        'encrypted-media' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'execution-while-not-rendered' => [
            'none' => false,
            '*' => true,
            'self' => false,
            'origins' => [],
        ],
        'execution-while-out-of-viewport' => [
            'none' => false,
            '*' => true,
            'self' => false,
            'origins' => [],
        ],
        'fullscreen' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'geolocation' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'gyroscope' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'magnetometer' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'microphone' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'midi' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'navigation-override' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'payment' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'picture-in-picture' => [
            'none' => false,
            '*' => true,
            'self' => false,
            'origins' => [],
        ],
        'publickey-credentials-get' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'screen-wake-lock' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'sync-xhr' => [
            'none' => false,
            '*' => true,
            'self' => false,
            'origins' => [],
        ],
        'usb' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'web-share' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
        'xr-spatial-tracking' => [
            'none' => false,
            '*' => false,
            'self' => false,
            'origins' => [],
        ],
    ],
    'csp' => [
        'enable' => true,
        'report-only' => false,
        'report-to' => '',
        'report-uri' => [],
        'block-all-mixed-content' => false,
        'upgrade-insecure-requests' => false,
        'base-uri' => [],
        'child-src' => [],
        'connect-src' => [],
        'default-src' => [],
        'font-src' => [],
        'form-action' => [],
        'frame-ancestors' => [],
        'frame-src' => [],
        'img-src' => [],
        'manifest-src' => [],
        'media-src' => [],
        'navigate-to' => [
            'unsafe-allow-redirects' => false,
        ],
        'object-src' => [],
        'plugin-types' => [],
        'prefetch-src' => [],
        'require-trusted-types-for' => [
            'script' => false,
        ],
        'sandbox' => [
            'enable' => false,
            'allow-downloads-without-user-activation' => false,
            'allow-forms' => false,
            'allow-modals' => false,
            'allow-orientation-lock' => false,
            'allow-pointer-lock' => false,
            'allow-popups' => false,
            'allow-popups-to-escape-sandbox' => false,
            'allow-presentation' => false,
            'allow-same-origin' => false,
            'allow-scripts' => false,
            'allow-storage-access-by-user-activation' => false,
            'allow-top-navigation' => false,
            'allow-top-navigation-by-user-activation' => false,
        ],
        'script-src' => [
            'none' => false,
            'self' => false,
            'report-sample' => false,
            'allow' => [],
            'schemes' => [],
            'unsafe-inline' => false,
            'unsafe-eval' => false,
            'unsafe-hashes' => false,
            'strict-dynamic' => false,
            'hashes' => [
                'sha256' => [],
                'sha384' => [ ],
                'sha512' => [],
            ],
        ],
        'script-src-attr' => [],
        'script-src-elem' => [],
        'style-src' => [],
        'style-src-attr' => [],
        'style-src-elem' => [],
        'trusted-types' => [
            'enable' => false,
            'allow-duplicates' => false,
            'default' => false,
            'policies' => [],
        ],
        'worker-src' => [],
    ],
];
